# Generated by Django 3.1.7 on 2021-03-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Venda',
        ),
    ]
